apps/course/urls.py
from django.urls import path,include
from . import views

app_name = 'course'

urlpatterns = [
    path('',views.course_index,name='course_index'),
    path('<int:course_id>/',views.course_detail,name='course_detail'),
    path('course_token/',views.course_token,name='course_token'),
    path('course_order/<int:course_id>/',views.course_order,name='course_order'),
    path('course_order_key/',views.course_order_key,name="course_order_key"),
    path('notify_view/',views.notify_view,name='notify_view')
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',views.index,name='index'),
    path('search/',include("haystack.urls")),
    path('cms/',include("apps.cms.urls")),
    path('news/',include("apps.news.urls")),
    path('account/', include("apps.xfzauth.urls")),
    path('course/',include("apps.course.urls")),
    path('payinfo/',include("apps.payinfo.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

apps/course/models.py
from django.db import models
from shortuuidfield import ShortUUIDField

class Course(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey('CourseCategory',on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher',on_delete=models.DO_NOTHING)
    video_url = models.URLField()
    cover_url = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

class CourseCategory(models.Model):
    name = models.CharField(max_length=100)


class Teacher(models.Model):
    username = models.CharField(max_length=100)
    avatar = models.URLField()
    jobtitle = models.CharField(max_length=100)
    profile = models.TextField()

#课程与分类是一对一的关系， 分类与课程是多对一的关系
#课程与讲师是多对一的关系


class CourseOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)
    course = models.ForeignKey("Course",on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("xfzauth.User",on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：代表的是支付宝支付。2：代表的是微信支付
    istype = models.SmallIntegerField(default=0)
    # 1：代表的是未支付。2：代表的是支付成功
    status = models.SmallIntegerField(default=1)

apps/course/views.py
from django.shortcuts import render
from .models import Course,CourseCategory,CourseOrder
from utils import restful
from django.conf import settings
from apps.xfzauth.decorators import xfz_login_required
from hashlib import md5
from django.shortcuts import reverse
from django.views.decorators.csrf import csrf_exempt
import time,hmac,os,hashlib
def course_index(request):
    context = {
        'courses':Course.objects.all()
    }
    return render(request,'course/course_index.html',context=context)

def course_detail(request,course_id):
    course = Course.objects.get(pk=course_id)
    buyed = CourseOrder.objects.filter(course=course,buyer=request.user,status=2).exists()
    context = {
        'course': course,
        'buyed': buyed
    }
    return render(request,'course/course_detail.html',context=context)

def course_token(request):
    # video：是视频文件的完整链接
    file = request.GET.get('video')

    course_id = request.GET.get('course_id')
    #判断是否购买了课程
    if not CourseOrder.objects.filter(course_id=course_id,buyer=request.user,status=2).exists():
        return restful.paramserror(message='请先购买课程！')

    expiration_time = int(time.time()) + 2 * 60 * 60

    USER_ID = settings.BAIDU_CLOUD_USER_ID
    USER_KEY = settings.BAIDU_CLOUD_USER_KEY

    # file=http://hemvpc6ui1kef2g0dd2.exp.bcevod.com/mda-igjsr8g7z7zqwnav/mda-igjsr8g7z7zqwnav.m3u8
    extension = os.path.splitext(file)[1]
    media_id = file.split('/')[-1].replace(extension, '')

    # unicode->bytes=unicode.encode('utf-8')bytes
    key = USER_KEY.encode('utf-8')
    message = '/{0}/{1}'.format(media_id, expiration_time).encode('utf-8')
    signature = hmac.new(key, message, digestmod=hashlib.sha256).hexdigest()
    token = '{0}_{1}_{2}'.format(signature, USER_ID, expiration_time)
    return restful.result(data={'token': token})

#限制登录状态下才能进行   (课程订单)
@xfz_login_required
def course_order(request,course_id):
    course = Course.objects.get(pk=course_id)
    order = CourseOrder.objects.create(course=course,buyer=request.user,status=1,amount=course.price)
    context = {
        'goods': {
            'thumbnail': course.cover_url,
            'title': course.title,
            'price': course.price
        },
        'order': order,
        # /course/notify_url/ 构建完整的url链接:build_absolute_uri
        'notify_url': request.build_absolute_uri(reverse('course:notify_view')),
        #执行完成以后返回的url
        'return_url': request.build_absolute_uri(reverse('course:course_detail',kwargs={"course_id":course.pk}))
    }
    return render(request,'course/course_order.html',context=context)

@xfz_login_required
def course_order_key(request):
    goodsname = request.POST.get("goodsname")
    istype = request.POST.get("istype")
    notify_url = request.POST.get("notify_url")
    orderid = request.POST.get("orderid")
    price = request.POST.get("price")
    return_url = request.POST.get("return_url")

    token = 'f083578bddcdbb3e490ba68ed92bfe88'
    uid = '09f18adb4f85817cab298f48'
    orderuid = str(request.user.pk)

    print('goodsname:',goodsname)
    print('istype:',istype)
    print('notify_url:',notify_url)
    print('orderid:',orderid)
    print('price:',price)
    print('return_url:',return_url)

    key = md5((goodsname + istype + notify_url + orderid + orderuid + price + return_url + token + uid).encode(
        "utf-8")).hexdigest()
    return restful.result(data={"key": key})


@csrf_exempt #关闭csrf保护 因为paysAPI服务器不会发送csrf_token
def notify_view(request):
    orderid = request.POST.get('orderid')
    print('='*10)
    print(orderid)
    print('='*10)
    CourseOrder.objects.filter(pk=orderid).update(status=2)
    return restful.ok()

front/templates/course/course_detail.html
{% extends 'base/front_base.html'%}

{% block title %}
    课程详情
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css' %}">
    <script src="{% static 'videojs/video.min.js' %}"></script>
    <script src="{% static 'videojs/videojs-contrib-hls.min.js' %}"></script>
    <script src="{% static 'videojs/videojs-contrib-quality-levels.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>
    <script src="{% static 'js/course_detail.min.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="course-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业课堂</a></li>
                </ul>
            </div>
        </div>

        <div class="wrapper">
            <div class="course-wrapper">
                <div class="course-info">
                    <p class="course-title">{{ course.title }}</p>
                    <div class="price-group">
                        <div class="share-group">
                            <span class="title">分享至：</span>
                            <a href="#" class="weixin share-item"></a>
                            <a href="#" class="weibo share-item"></a>
                        </div>
                        <div class="buy-group">
                            {% if course.price > 0 %}
                                <span class="price pay">￥{{ course.price }}</span>
                                <a href="{% url 'course:course_order' course_id=course.pk%}" class="buy-btn">立即购买</a>
                            {% else %}
                                <span class="price free">免费</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="video-group">
                <span id="video-info" hidden data-video-url="{{ course.video_url }}" data-cover-url="{{ course.cover_url }}"></span>
                <div id="playercontainer">

                </div>
            </div>
            <div class="bottom-wrapper">
                <div class="course-detail-wrapper">
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="atatar-group">
                                <img src="{{ course.teacher.avatar }}" alt="">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">{{ course.teacher.username }}</p>
                                <p class="teacher-desc">{{ course.teacher.jobtitle }}</p>
                            </div>
                        </div>
                        <p class="item-content">
                            {{ course.profile|safe }}
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程简介</p>
                        <p class="item-content">
                            {{ course.profile|safe }}
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="atatar-group">
                                <img src="https://static-image.xfz.cn/1508120374_220.jpg" alt="">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">乔继英</p>
                                <p class="teacher-desc">专业投资人；一线基金董事总经理</p>
                            </div>
                        </div>
                        <p class="item-content">
                            乔继英，专业投资人，一线基金董事总经理，十五年以上研发、市场销售、投资经验，投资领域覆盖天使投资、中早期风险投资、PE投资、并购、母基金FOF投资等领域。代表案例：华润凤凰（1515.HK）、微芯生物、二毛照护、九鼎美元基金等。个人间接投资摩拜单车、硅谷大数据公司Palantir等。曾在淡马锡祥峰投资、蓝驰创投、启迪创投等工作，世界五百强公司研发、市场销售主管。北京市高精尖产业基金评审组长、知名证券公司专业专家。清华大学本科、医学院博士、校友导师，曾与哈佛大学合作课题；香港中文大学金融MBA、客座讲师。
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="atatar-group">
                                <img src="https://static-image.xfz.cn/1508120374_220.jpg" alt="">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">乔继英</p>
                                <p class="teacher-desc">专业投资人；一线基金董事总经理</p>
                            </div>
                        </div>
                        <p class="item-content">
                            乔继英，专业投资人，一线基金董事总经理，十五年以上研发、市场销售、投资经验，投资领域覆盖天使投资、中早期风险投资、PE投资、并购、母基金FOF投资等领域。代表案例：华润凤凰（1515.HK）、微芯生物、二毛照护、九鼎美元基金等。个人间接投资摩拜单车、硅谷大数据公司Palantir等。曾在淡马锡祥峰投资、蓝驰创投、启迪创投等工作，世界五百强公司研发、市场销售主管。北京市高精尖产业基金评审组长、知名证券公司专业专家。清华大学本科、医学院博士、校友导师，曾与哈佛大学合作课题；香港中文大学金融MBA、客座讲师。
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="atatar-group">
                                <img src="https://static-image.xfz.cn/1508120374_220.jpg" alt="">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">乔继英</p>
                                <p class="teacher-desc">专业投资人；一线基金董事总经理</p>
                            </div>
                        </div>
                        <p class="item-content">
                            乔继英，专业投资人，一线基金董事总经理，十五年以上研发、市场销售、投资经验，投资领域覆盖天使投资、中早期风险投资、PE投资、并购、母基金FOF投资等领域。代表案例：华润凤凰（1515.HK）、微芯生物、二毛照护、九鼎美元基金等。个人间接投资摩拜单车、硅谷大数据公司Palantir等。曾在淡马锡祥峰投资、蓝驰创投、启迪创投等工作，世界五百强公司研发、市场销售主管。北京市高精尖产业基金评审组长、知名证券公司专业专家。清华大学本科、医学院博士、校友导师，曾与哈佛大学合作课题；香港中文大学金融MBA、客座讲师。
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="atatar-group">
                                <img src="https://static-image.xfz.cn/1508120374_220.jpg" alt="">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">乔继英</p>
                                <p class="teacher-desc">专业投资人；一线基金董事总经理</p>
                            </div>
                        </div>
                        <p class="item-content">
                            乔继英，专业投资人，一线基金董事总经理，十五年以上研发、市场销售、投资经验，投资领域覆盖天使投资、中早期风险投资、PE投资、并购、母基金FOF投资等领域。代表案例：华润凤凰（1515.HK）、微芯生物、二毛照护、九鼎美元基金等。个人间接投资摩拜单车、硅谷大数据公司Palantir等。曾在淡马锡祥峰投资、蓝驰创投、启迪创投等工作，世界五百强公司研发、市场销售主管。北京市高精尖产业基金评审组长、知名证券公司专业专家。清华大学本科、医学院博士、校友导师，曾与哈佛大学合作课题；香港中文大学金融MBA、客座讲师。
                        </p>
                    </div>
                </div>
                <div class="recommend-wrapper">
                    <p class="recommend-title">推荐课程</p>
                    <ul class="recommend-group">
                        <li>
                            <div class="recommend-info">
                                <p class="title">创业公司如何做估值</p>
                                <p class="teacher">邱总CEO</p>
                            </div>
                            <div class="thumbnail-group">
                                <img src="https://static-image.xfz.cn/1554346304_52.png-course.list.small" alt="">
                            </div>
                        </li>
                        <li>
                            <div class="recommend-info">
                                <p class="title">创业公司如何做估值</p>
                                <p class="teacher">邱总CEO</p>
                            </div>
                            <div class="thumbnail-group">
                                <img src="https://static-image.xfz.cn/1554346304_52.png-course.list.small" alt="">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/course/course_index.html
{% extends 'base/front_base.html'%}

{% block title %}
    课程首页
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_index.min.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="course-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业课堂</a></li>
                </ul>
            </div>
        </div>

        <div class="wrapper">
            <ul class="course-list">
                {% for course in courses %}
                    <li>
                        <a href="{% url 'course:course_detail' course_id=course.pk %}">
                            <div class="thumbnail-group">
                                <img src="{{ course.cover_url }}" alt="">
                            </div>
                            <div class="course-info">
                                <p class="title">{{ course.title }}</p>
                                <p class="author">{{ course.teacher.username }}</p>
                                <p class="price-group">
                                    {% if course.price > 0 %}
                                        <span class="pay">￥{{ course.price }}</span>
                                    {% else %}
                                        <span class="free">免费</span>
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </li>
                {% endfor %}


            </ul>
        </div>
    </div>
{% endblock %}

front/templates/course/course_order.html
{% extends 'base/front_base.html' %}

{% block title %}
确认订单
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/common/header.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/common/footer.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/common/body.min.css' %}">
    <style>
        .table{
            width: 100%;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            background: #eaeaea;
            text-align: center;
        }
        .table{
            border-spacing: 20px;
        }
        .table img{
            width: 120px;
            height: 68px;
            float: left;
        }
        .table .title{
            margin-left: 10px;
        }
        .pay-way label{
            float: right;
        }
        .pay-way span{
            border: 1px solid #ccc;
            position: relative;
            top: 20px;
        }
        .pay-way .zfb-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            cursor: pointer;
            background: url("http://study.163.com/res/images/pay/payList.png");
            background-position: -140px 0;
            background-size: 300% 200%;
            margin-right:20px;
        }
        .pay-way .wx-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            position: relative;
            cursor: pointer;
        }
        .pay-way .wx-btn img{
            top: 12px;
            left: 16px;
            position: absolute;
        }
        .submit-group{
            overflow: hidden;
            padding: 60px 0;
        }
        .submit-btn{
            display: block;
            text-align: center;
            width: 136px;
            height:49px;
            line-height: 49px;
            background: url("http://s.stu.126.net/res/images/pay/payBtns.png?c9b6b849b38cca45b160a96802575ac8") no-repeat 4449px 4449px;
            background-position: 0 -302px;
            border: none;
            cursor: pointer;
            color: #fff;
            font-size: 16px;
            float: right;
        }
        .submit-btn:hover{
            background-position: -139px -302px;
        }
    </style>
    <script>
        $(function () {
            var submitBtn = $("#submit-btn");
            submitBtn.click(function (event) {
                event.preventDefault();
                var goodsname = $("input[name='goodsname']").val();
                var istype = $("input[name='istype']:checked").val(); //checked只会去找选中的值
                var notify_url = $("input[name='notify_url']").val();
                var orderid = $("input[name='orderid']").val();
                var price = $("input[name='price']").val();
                var return_url = $("input[name='return_url']").val();
                xfzajax.post({
                    'url': '/course/course_order_key/',
                    'data': {
                        'goodsname': goodsname,
                        'istype': istype,
                        'notify_url': notify_url,
                        'orderid': orderid,
                        'price': price,
                        'return_url': return_url
                    },
                    'success': function (result) {
                        if(result['code'] === 200){
                            var key = result['data']['key'];
                            var keyInput = $("input[name='key']");
                            keyInput.val(key);
                            $("#pay-form").submit();
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <table class="table">
            <thead>
                <tr>
                    <th>商品名称</th>
                    <th>单价(元)</th>
                    <th>小计（元）</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align="left">
                        <a href="#">
                            <img class="thumbnail" src="{{ goods.thumbnail }}" alt="">
                            <span class="title">{{ goods.title }}</span>
                        </a>
                    </td>
                    <td>{{ goods.price }}</td>
                    <td>{{ goods.price }}</td>
                </tr>
            </tbody>
        </table>
            <form action="https://pay.bearsoftware.net.cn/" method="post" id="pay-form">
                <input type="hidden" name="uid" value="09f18adb4f85817cab298f48">
                <input type="hidden" name="price" value="{{ goods.price }}">
                <input type="hidden" name="notify_url" value="{{ notify_url }}">
                <input type="hidden" name="return_url" value="{{ return_url }}">
                <input type="hidden" name="orderid" value="{{ order.pk }}">
                <input type="hidden" name="orderuid" value="{{ request.user.pk }}">
                <input type="hidden" name="goodsname" value="{{ goods.title }}">
                <input type="hidden" name="key" value="">
            <div class="pay-way">
                <label for="istype-wx">
                    <input id="istype-wx" type="radio" name="istype" value="2">
                    <span class="wx-btn">
                        <img src="http://nos.netease.com/test-edu-image/1BD9F69D6760CE1508D2269864AA54F8.png" alt="">
                    </span>
                </label>
                <label for="istype-zfb">
                    <input id="istype-zfb" type="radio" name="istype" value="1" checked>
                    <span class="zfb-btn"></span>
                </label>
                <div style="clear: both;"></div>
            </div>
            <div class="submit-group">
                <input type="submit" value="去支付" id="submit-btn" class="submit-btn">
            </div>
        </form>
        </div>
    </div>
{% endblock %}