apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [
    path('',views.index,name='index'),
    path('payinfo_order/',views.payinfo_order,name='payinfo_order'),
    path('notify_url/',views.notify_view,name='notify_view'),
    path('download/',views.download,name='download')
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',views.index,name='index'),
    path('search/',include("haystack.urls")),
    path('cms/',include("apps.cms.urls")),
    path('news/',include("apps.news.urls")),
    path('account/', include("apps.xfzauth.urls")),
    path('course/',include("apps.course.urls")),
    path('payinfo/',include("apps.payinfo.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

apps/payinfo/models.py
#encoding:utf-8
from django.db import models
from shortuuidfield import ShortUUIDField
class Payinfo(models.Model):
    title = models.CharField(max_length=100)
    profile = models.CharField(max_length=200)
    price = models.FloatField()
    path = models.FilePathField()

class PayinfoOrder(models.Model):
    uid = ShortUUIDField(primary_key=True) #唯一字段
    payinfo = models.ForeignKey("Payinfo", on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("xfzauth.User", on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：代表的是支付宝支付。2：代表的是微信支付
    istype = models.SmallIntegerField(default=0)
    # 1：代表的是未支付。2：代表的是支付成功
    status = models.SmallIntegerField(default=1)

apps/payinfo/views.py
from django.shortcuts import render
from .models import Payinfo,PayinfoOrder
from apps.xfzauth.decorators import xfz_login_required
from django.views.decorators.csrf import csrf_exempt
from utils import restful
from django.shortcuts import reverse
from django.http import FileResponse,Http404
from django.conf import settings
import os

def index(request):
    context = {
        'payinfos': Payinfo.objects.all()
    }
    return render(request,'payinfo/payinfo.html',context=context)

@xfz_login_required
def payinfo_order(request):
    payinfo_id = request.GET.get('payinfo_id')
    payinfo = Payinfo.objects.get(pk=payinfo_id)
    order = PayinfoOrder.objects.create(payinfo=payinfo,buyer=request.user,status=1,amount=payinfo.price)
    context = {
        'goods': {
            'thumbnail': '',
            'price': payinfo.price,
            'title': payinfo.title
        },
        'order': order,
        'notify_url':request.build_absolute_uri(reverse('payinfo:notify_view')),
        'return_url': request.build_absolute_uri(reverse('payinfo:index'))
    }
    return render(request,'course/course_order.html',context=context)

@csrf_exempt
def notify_view(request):
    orderid = request.POST.get("orderid")
    PayinfoOrder.objects.filter(pk=orderid).update(status=2)
    return restful.ok()

@xfz_login_required
def download(request):
    payinfo_id = request.GET.get('payinfo_id')
    order = PayinfoOrder.objects.filter(payinfo_id=payinfo_id,buyer=request.user,status=2).first()
    if order:
        payinfo = order.payinfo
        path = payinfo.path
        # /a/xx.png = ['',a,xx.png]
        fp = open(os.path.join(settings.MEDIA_ROOT,path),'rb')
        response = FileResponse(fp)
        response['Content-Type'] = 'image/jpeg'
        response['Content-Disposition'] = 'attachment;filename="%s"'%path.split("/")[-1]
        return response
    else:
        return Http404()

front/templates/payinfo/payinfo.html
{% extends 'base/front_base.html'%}

{% load payinfo_filters %}

{% block title %}
    付费资讯
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/payinfo/payinfo.min.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="thumbnail">
                    <img src="https://www.xfz.cn/static/build/images/web-shopxfz-banner.jpg" alt="">
                </div>
                <ul class="pay-wrapper">
                    {% for payinfo in payinfos %}
                        <li class="pay-group">
                            {% with payinfo|is_buyed:user as buyed %}
                                {% if buyed %}
                                    <a href="{% url 'payinfo:download' %}?payinfo_id={{ payinfo.pk }}">
                                {% else %}
                                    <a href="{% url 'payinfo:payinfo_order' %}?payinfo_id={{ payinfo.pk }}">
                                {% endif %}
                                <div class="pay-thumbnail">
                                    <img src="https://www.xfz.cn/static/build/images/web-bp-pc.png" alt="">
                                </div>
                                <div class="pay-info">
                                    <p class="pay-title">
                                        {{ payinfo.title }}
                                    </p>
                                    <p class="pay-desc">
                                        {{ payinfo.profile }}
                                    </p>
                                    <span class="pay-number">
                                        {% if buyed %}
                                            点击下载
                                        {% else %}
                                            ￥{{ payinfo.price }}
                                        {% endif %}
                                    </span>
                                </div>
                            {% endwith %}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}